Sun, 03 Jan 2016 21:04:11 measure.py[line:13] DEBUG this is the message !
